### ISSUE TITLE
Use official darknet version.

### ISSUE THREAD

**Issue by chanfr** [JdeRobot/DetectionMetrics#112]
The idea is to use the official darknet version instead of a modified one. All extra files should be included in this repo in a "wrappers" folder.

**Comment by sleep-404** [comment]
How does dl-Detection suite work ? where can I get the basic skeleton or structure of detection suite ?

**Comment by vinay0410** [comment]
Hi @sleep-404 , I just saw this issue. I would recommend running darknet inferencer using DetectionSuite, and look into the code of `DarknetInferencer.cpp` to get a basic idea of how it uses the darknet api to run inferences.
The aim of this issue is to shift from `Jderobot/darknet` to official `darknet` repo.
