### ISSUE TITLE
Error Running Autoevaluator

### ISSUE THREAD

**Issue by dbutragueno** [JdeRobot/DetectionMetrics#142]
Hi!

I have been trying Autoevaluator tool from Detection Suite using Caffe and three differents trained models. I created my config file like that:

<img width="1325" alt="Captura de pantalla 2019-06-06 a las 22 55 51" src="https://user-images.githubusercontent.com/18295154/59065973-4122d680-88ae-11e9-90e5-265c9d96c6b0.png">

After, I ran the app but a Segmentation fault (core dumped) error showed up:

<img width="612" alt="Captura de pantalla 2019-06-06 a las 22 57 26" src="https://user-images.githubusercontent.com/18295154/59066064-73343880-88ae-11e9-9346-f4358f3dd836.png">

This is due to a denied access to memory but I don't know the reason.

Anyone knows what could be the problem? Is this tool working currently?

Thanks!

**Comment by DavidButra** [comment]
Hello @vinay0410,

do you know something about that?

Regards!

**Comment by DavidButra** [comment]
Hi @vinay0410,

I think this problem is because of the inferencer I am using. Changing my config file and using, for example keras, the script KerasInferencer.cpp runs and it fails because Keras is not install in my pc. Because I'm using Caffe, is it necessary to set parameters like scaling factor, input size or mean subtraction in my config file? If so, how do I due configure it?

Thanks!

**Comment by sleep-404** [comment]
@DavidButra , I will once look into what is Autoevaluator and how does it work and get back to you soon. And sorry for the delayed response :)

**Comment by vinay0410** [comment]
Yes, @DavidButra you will have to set additional parameters like scaling factor, input size etc, in the config file. I will just try it myself, and let you know, how to set them.
