### ISSUE TITLE
Travis CI's build are failing

### ISSUE THREAD

**Issue by vinay0410** [JdeRobot/DetectionMetrics#148]
I think we should first fix Ubuntu's build, and then move on to fixing osx's builds.
https://travis-ci.org/JdeRobot/DetectionSuite

**Comment by sergiopaniego** [comment]
The error prompted is the following:
W: GPG error: http://packages.ros.org/ros/ubuntu xenial InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 

Searching for a possible solution I have found this thread:
https://answers.ros.org/question/325039/apt-update-fails-cannot-install-pkgs-key-not-working/

I don't know if it could help us. I'm not sure how to add it to the .travis.yml file

**Comment by hogum** [comment]
I'd like to try at adding the suggestions provided on the thread to the `.travis.yml` file @sergiopaniego

**Comment by Surajpatra700** [comment]
I would like to work upon this issue

**Comment by Keshav-Dadhich** [comment]
I think I can work on this issue
